Remove `region` for AWS provider.
This fixes the following Terraform error:

```
Error: Missing required argument

  on api_gateway.tf line 1, in provider "aws":
   1: provider "aws" {

The argument "region" is required, but no definition was found.
```