Use `tolist()` to make record indexing compatible with new Terraform.
https://github.com/hashicorp/terraform/issues/26366#issuecomment-698563615

This fixes the following errors:

```
Error: Invalid index

  on api_gateway.tf line 33, in resource "aws_route53_record" "cert_validation":
  33:   name    = "${aws_acm_certificate.cert.domain_validation_options.0.resource_record_name}"

This value does not have any indices.
```